on: [push]

permissions: write-all

jobs:
  archive:
    runs-on: ubuntu-latest
    name: Build archive
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Folk Archive
        id: builder
        uses: Folk-Archive/archive-actions@v0.1.7
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          name: site
          path: ./site
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
